### PR TITLE
Add ./yarn symlink.

### PR DESCRIPTION
**Pull request by carljm**
## Cute animal pic
_Because everyone likes pictures of animals._

## Description
_The commit messages say what you did; this should explain why and how._

I want to use the local version of yarn bundled in this repo, without needing a global `yarn` on my path that will redirect to it. So this is my simple solution that allows me to do e.g. `./yarn test` without needing a global yarn install. If there's a better way to do this, I'm all ears, but this way works for me and is harmless to anyone else's workflow.

---

## Reviewer tasks:

- [ ] Reviewed code

### CODE REVIEW

**Comment by carljm** [comment]
@jgerigmeyer This is a one-liner, if you have a chance to look at it soon, it would improve my workflow on the other PR :)

**Review by jgerigmeyer — APPROVED** [review]
Hm. I guess this essentially is a shortcut, doing the exact same thing as the existing `.yarnrc` file. I don't love it long-term -- it adds another place to hardcode the current yarn version -- but it's fine for now.

Is there a compelling reason not to want yarn installed globally? We require other global tools (e.g. node)...

**Comment by carljm** [comment]
Yeah, you're right, this symlink will need updating whenever we update Yarn.

I guess there's no compelling reason, it's just that I don't use yarn for any other project, and I like to minimize the amount of global setup I do for stuff that I don't often use, especially when it's only actually needed as a workaround to get something on my PATH, I'm not even going to ever use the globally installed one to do anything.

If you'd rather, I can also do this locally-only and gitignore it.

**Comment by jgerigmeyer** [comment]
🤔 I think I would prefer that? Given the use-case is pretty specific to your setup/approach. I would generally expect devs to have yarn installed globally. 🤷‍♂

**Pull request closed without merging**
